export const rows = [
  {
    rank: "1",
    title: "Brass: Birmingham",
    titleJP: "ブラス：バーミンガム",
    year: "2018",
    rating: "8.414",
    weight: "3.87",
    designers: ["Gavan Brown", "Matt Tolman", "Martin Wallace"],
    url: "https://boardgamegeek.com/boardgame/224517/brass-birmingham",
  },
  {
    rank: "2",
    title: "Pandemic Legacy: Season 1",
    titleJP: "パンデミック：レガシー シーズン1",
    year: "2015",
    rating: "8.376",
    weight: "2.83",
    designers: ["Rob Daviau", "Matt Leacock"],
    url: "https://boardgamegeek.com/boardgame/161936/pandemic-legacy-season-1",
  },
  {
    rank: "3",
    title: "Gloomhaven",
    titleJP: "グルームヘイヴン",
    year: "2017",
    rating: "8.345",
    weight: "3.91",
    designers: ["Isaac Childres"],
    url: "https://boardgamegeek.com/boardgame/174430/gloomhaven",
  },
  {
    rank: "4",
    title: "Ark Nova",
    titleJP: "アーク・ノヴァ　新たなる方舟",
    year: "2021",
    rating: "8.339",
    weight: "3.77",
    designers: ["Mathias Wigge"],
    url: "https://boardgamegeek.com/boardgame/342942/ark-nova",
  },
  {
    rank: "5",
    title: "Twilight Imperium: Fourth Edition",
    titleJP: "トワイライト・インぺリウム第4版",
    year: "2017",
    rating: "8.238",
    weight: "4.32",
    designers: ["Dane Beltrami", "Corey Konieczka", "Christian T. Petersen"],
    url: "https://boardgamegeek.com/boardgame/233078/twilight-imperium-fourth-edition",
  },
  {
    rank: "6",
    title: "Dune: Imperium",
    titleJP: "デューン　砂の惑星　インペリウム",
    year: "2020",
    rating: "8.232",
    weight: "3.05",
    designers: ["Paul Dennen"],
    url: "https://boardgamegeek.com/boardgame/316554/dune-imperium",
  },
  {
    rank: "7",
    title: "Terraforming Mars",
    titleJP: "テラフォーミング・マーズ",
    year: "2016",
    rating: "8.208",
    weight: "3.26",
    designers: ["Jacob Fryxelius"],
    url: "https://boardgamegeek.com/boardgame/167791/terraforming-mars",
  },
  {
    rank: "8",
    title: "War of the Ring: Second Edition",
    titleJP: "",
    year: "2011",
    rating: "8.189",
    weight: "4.22",
    designers: ["Roberto Di Meglio", "Marco Maggi", "Francesco Nepitello"],
    url: "https://boardgamegeek.com/boardgame/115746/war-of-the-ring-second-edition",
  },
  {
    rank: "9",
    title: "Star Wars: Rebellion",
    titleJP: "",
    year: "2016",
    rating: "8.17",
    weight: "3.74",
    designers: ["Corey Konieczka"],
    url: "https://boardgamegeek.com/boardgame/187645/star-wars-rebellion",
  },
  {
    rank: "10",
    title: "Gloomhaven: Jaws of the Lion",
    titleJP: "グルームヘイヴン スタートセット 獅子のあぎと",
    year: "2020",
    rating: "8.153",
    weight: "3.64",
    designers: ["Isaac Childres"],
    url: "https://boardgamegeek.com/boardgame/291457/gloomhaven-jaws-of-the-lion",
  },
  {
    rank: "11",
    title: "Spirit Island",
    titleJP: "スピリット・アイランド",
    year: "2017",
    rating: "8.145",
    weight: "4.07",
    designers: ["R. Eric Reuss"],
    url: "https://boardgamegeek.com/boardgame/162886/spirit-island",
  },
  {
    rank: "12",
    title: "Gaia Project",
    titleJP: "テラミスティカ：ガイアプロジェクト",
    year: "2017",
    rating: "8.108",
    weight: "4.39",
    designers: ["Jens Drögemüller", "Helge Ostertag"],
    url: "https://boardgamegeek.com/boardgame/220308/gaia-project",
  },
  {
    rank: "13",
    title: "Twilight Struggle",
    titleJP: "トワイライト・ストラグル",
    year: "2005",
    rating: "8.065",
    weight: "3.61",
    designers: ["Ananda Gupta", "Jason Matthews"],
    url: "https://boardgamegeek.com/boardgame/12333/twilight-struggle",
  },
  {
    rank: "14",
    title: "Through the Ages: A New Story of Civilization",
    titleJP: "スルー･ジ･エイジズ:新たなる文明の物語",
    year: "2015",
    rating: "8.05",
    weight: "4.44",
    designers: ["Vlaada Chvátil"],
    url: "https://boardgamegeek.com/boardgame/182028/through-the-ages-a-new-story-of-civilization",
  },
  {
    rank: "15",
    title: "Great Western Trail",
    titleJP: "グレート ウエスタン トレイル",
    year: "2016",
    rating: "8.019",
    weight: "3.7",
    designers: ["Alexander Pfister"],
    url: "https://boardgamegeek.com/boardgame/193738/great-western-trail",
  },
  {
    rank: "16",
    title: "The Castles of Burgundy",
    titleJP: "",
    year: "2011",
    rating: "8.016",
    weight: "2.98",
    designers: ["Stefan Feld"],
    url: "https://boardgamegeek.com/boardgame/84876/the-castles-of-burgundy",
  },
  {
    rank: "17",
    title: "Scythe",
    titleJP: "大鎌戦役",
    year: "2016",
    rating: "7.984",
    weight: "3.45",
    designers: ["Jamey Stegmaier"],
    url: "https://boardgamegeek.com/boardgame/169786/scythe",
  },
  {
    rank: "18",
    title: "Eclipse: Second Dawn for the Galaxy",
    titleJP: "エクリプス〜新たなる銀河の夜明け〜",
    year: "2020",
    rating: "7.979",
    weight: "3.64",
    designers: ["Touko Tahkokallio"],
    url: "https://boardgamegeek.com/boardgame/246900/eclipse-second-dawn-for-the-galaxy",
  },
  {
    rank: "19",
    title: "7 Wonders Duel",
    titleJP: "世界の七不思議:デュエル",
    year: "2015",
    rating: "7.971",
    weight: "2.23",
    designers: ["Antoine Bauza", "Bruno Cathala"],
    url: "https://boardgamegeek.com/boardgame/173346/7-wonders-duel",
  },
  {
    rank: "20",
    title: "Brass: Lancashire",
    titleJP: "ブラス：ランカシャー",
    year: "2007",
    rating: "7.962",
    weight: "3.85",
    designers: ["Martin Wallace"],
    url: "https://boardgamegeek.com/boardgame/28720/brass-lancashire",
  },
  {
    rank: "21",
    title: "Nemesis",
    titleJP: "ネメシス",
    year: "2018",
    rating: "7.954",
    weight: "3.47",
    designers: ["Adam Kwapiński"],
    url: "https://boardgamegeek.com/boardgame/167355/nemesis",
  },
  {
    rank: "22",
    title: "Clank! Legacy: Acquisitions Incorporated",
    titleJP: "",
    year: "2019",
    rating: "7.947",
    weight: "2.74",
    designers: ["Andy Clautice", "Paul Dennen"],
    url: "https://boardgamegeek.com/boardgame/266507/clank-legacy-acquisitions-incorporated",
  },
  {
    rank: "23",
    title: "A Feast for Odin",
    titleJP: "オーディンの祝祭",
    year: "2016",
    rating: "7.943",
    weight: "3.86",
    designers: ["Uwe Rosenberg"],
    url: "https://boardgamegeek.com/boardgame/177736/a-feast-for-odin",
  },
  {
    rank: "24",
    title: "Concordia",
    titleJP: "コンコルディア",
    year: "2013",
    rating: "7.941",
    weight: "2.99",
    designers: ["Mac Gerdts"],
    url: "https://boardgamegeek.com/boardgame/124361/concordia",
  },
  {
    rank: "25",
    title: "Frosthaven",
    titleJP: "",
    year: "2022",
    rating: "7.91",
    weight: "4.38",
    designers: ["Isaac Childres"],
    url: "https://boardgamegeek.com/boardgame/295770/frosthaven",
  },
  {
    rank: "26",
    title: "Great Western Trail: Second Edition",
    titleJP: "グレート・ウエスタン・トレイル第2版",
    year: "2021",
    rating: "7.906",
    weight: "3.72",
    designers: ["Alexander Pfister"],
    url: "https://boardgamegeek.com/boardgame/341169/great-western-trail-second-edition",
  },
  {
    rank: "27",
    title: "Arkham Horror: The Card Game",
    titleJP: "アーカムホラー ザ・カードゲーム",
    year: "2016",
    rating: "7.9",
    weight: "3.54",
    designers: ["Nate French", "MJ Newman"],
    url: "https://boardgamegeek.com/boardgame/205637/arkham-horror-the-card-game",
  },
  {
    rank: "28",
    title: "Lost Ruins of Arnak",
    titleJP: "アルナックの失われし遺跡",
    year: "2020",
    rating: "7.895",
    weight: "2.92",
    designers: ["Elwen", "Mín"],
    url: "https://boardgamegeek.com/boardgame/312484/lost-ruins-of-arnak",
  },
  {
    rank: "29",
    title: "Wingspan",
    titleJP: "ウイングスパン",
    year: "2019",
    rating: "7.891",
    weight: "2.47",
    designers: ["Elizabeth Hargrave"],
    url: "https://boardgamegeek.com/boardgame/266192/wingspan",
  },
  {
    rank: "30",
    title: "Terra Mystica",
    titleJP: "テラミスティカ",
    year: "2012",
    rating: "7.89",
    weight: "3.97",
    designers: ["Jens Drögemüller", "Helge Ostertag"],
    url: "https://boardgamegeek.com/boardgame/120677/terra-mystica",
  },
  {
    rank: "31",
    title: "Root",
    titleJP: "ルート",
    year: "2018",
    rating: "7.884",
    weight: "3.81",
    designers: ["Cole Wehrle"],
    url: "https://boardgamegeek.com/boardgame/237182/root",
  },
  {
    rank: "32",
    title: "Too Many Bones",
    titleJP: "",
    year: "2017",
    rating: "7.873",
    weight: "3.85",
    designers: ["Josh J. Carlson", "Adam Carlson"],
    url: "https://boardgamegeek.com/boardgame/192135/too-many-bones",
  },
  {
    rank: "33",
    title: "Orléans",
    titleJP: "オルレアン",
    year: "2014",
    rating: "7.871",
    weight: "3.03",
    designers: ["Reiner Stockhausen"],
    url: "https://boardgamegeek.com/boardgame/164928/orleans",
  },
  {
    rank: "34",
    title: "Mage Knight Board Game",
    titleJP: "",
    year: "2011",
    rating: "7.853",
    weight: "4.37",
    designers: ["Vlaada Chvátil"],
    url: "https://boardgamegeek.com/boardgame/96848/mage-knight-board-game",
  },
  {
    rank: "35",
    title: "Barrage",
    titleJP: "バラージ",
    year: "2019",
    rating: "7.85",
    weight: "4.12",
    designers: ["Tommaso Battista", "Simone Luciani"],
    url: "https://boardgamegeek.com/boardgame/251247/barrage",
  },
  {
    rank: "36",
    title: "Everdell",
    titleJP: "エバーデール",
    year: "2018",
    rating: "7.843",
    weight: "2.83",
    designers: ["James A. Wilson"],
    url: "https://boardgamegeek.com/boardgame/199792/everdell",
  },
  {
    rank: "37",
    title: "The Crew: Mission Deep Sea",
    titleJP: "ザ・クルー　深海に眠る遺跡",
    year: "2021",
    rating: "7.842",
    weight: "2.03",
    designers: ["Thomas Sing"],
    url: "https://boardgamegeek.com/boardgame/324856/the-crew-mission-deep-sea",
  },
  {
    rank: "38",
    title: "Viticulture Essential Edition",
    titleJP: "ワイナリーの四季",
    year: "2015",
    rating: "7.835",
    weight: "2.89",
    designers: ["Jamey Stegmaier", "Alan Stone"],
    url: "https://boardgamegeek.com/boardgame/183394/viticulture-essential-edition",
  },
  {
    rank: "39",
    title: "Dune: Imperium – Uprising",
    titleJP: "デューン　砂の惑星　インペリウム　反乱",
    year: "2023",
    rating: "7.834",
    weight: "3.46",
    designers: ["Paul Dennen"],
    url: "https://boardgamegeek.com/boardgame/397598/dune-imperium-uprising",
  },
  {
    rank: "40",
    title: "Heat: Pedal to the Metal",
    titleJP: "ヒート",
    year: "2022",
    rating: "7.799",
    weight: "2.19",
    designers: ["Asger Harding Granerud", "Daniel Skjold Pedersen"],
    url: "https://boardgamegeek.com/boardgame/366013/heat-pedal-to-the-metal",
  },
  {
    rank: "41",
    title: "Marvel Champions: The Card Game",
    titleJP: "",
    year: "2019",
    rating: "7.798",
    weight: "2.94",
    designers: ["Michael Boggs"],
    url: "https://boardgamegeek.com/boardgame/285774/marvel-champions-the-card-game",
  },
  {
    rank: "42",
    title: "Food Chain Magnate",
    titleJP: "フードチェーンマグネイト",
    year: "2015",
    rating: "7.797",
    weight: "4.2",
    designers: ["Jeroen Doumen", "Joris Wiersinga"],
    url: "https://boardgamegeek.com/boardgame/175914/food-chain-magnate",
  },
  {
    rank: "43",
    title: "Pax Pamir: Second Edition",
    titleJP: "パックス・パミール　第２版",
    year: "2019",
    rating: "7.792",
    weight: "3.86",
    designers: ["Cole Wehrle"],
    url: "https://boardgamegeek.com/boardgame/256960/pax-pamir-second-edition",
  },
  {
    rank: "44",
    title: "Underwater Cities",
    titleJP: "アンダーウォーターシティーズ",
    year: "2018",
    rating: "7.783",
    weight: "3.58",
    designers: ["Vladimír Suchý"],
    url: "https://boardgamegeek.com/boardgame/247763/underwater-cities",
  },
  {
    rank: "45",
    title: "Puerto Rico",
    titleJP: "",
    year: "2002",
    rating: "7.772",
    weight: "3.27",
    designers: ["Andreas Seyfarth"],
    url: "https://boardgamegeek.com/boardgame/3076/puerto-rico",
  },
  {
    rank: "46",
    title: "Kanban EV",
    titleJP: "カンバンEV",
    year: "2020",
    rating: "7.771",
    weight: "4.3",
    designers: ["Vital Lacerda"],
    url: "https://boardgamegeek.com/boardgame/284378/kanban-ev",
  },
  {
    rank: "47",
    title: "Crokinole",
    titleJP: "クロキノール",
    year: "1876",
    rating: "7.769",
    weight: "1.23",
    designers: ["(Uncredited)"],
    url: "https://boardgamegeek.com/boardgame/521/crokinole",
  },
  {
    rank: "48",
    title: "Cascadia",
    titleJP: "カスカディア",
    year: "2021",
    rating: "7.766",
    weight: "1.85",
    designers: ["Randy Flynn"],
    url: "https://boardgamegeek.com/boardgame/295947/cascadia",
  },
  {
    rank: "49",
    title: "Caverna: The Cave Farmers",
    titleJP: "カヴェルナ: 洞窟の農夫たち",
    year: "2013",
    rating: "7.759",
    weight: "3.78",
    designers: ["Uwe Rosenberg"],
    url: "https://boardgamegeek.com/boardgame/102794/caverna-the-cave-farmers",
  },
  {
    rank: "50",
    title: "Anachrony",
    titleJP: "アナクロニー",
    year: "2017",
    rating: "7.753",
    weight: "4.01",
    designers: ["Dávid Turczi"],
    url: "https://boardgamegeek.com/boardgame/185343/anachrony",
  },
];
